[versions]
activity-compose = "1.11.0"
agp = "8.13.0"
androidx-startup-runtime = "1.2.0"
core-splashscreen = "1.0.1"
core-google-shortcuts = "1.1.0"
lifecycle-runtime-ktx = "2.9.4"
gson = "2.13.2"
kotlin = "2.2.21"
core-ktx = "1.17.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
navigation-safeargs = "2.9.5"
kotlin-coroutines = "1.10.2"
compose-compiler = "1.5.15"
compose-bom = "2025.10.01"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-core-google-shortcuts = { module = "androidx.core:core-google-shortcuts", version.ref = "core-google-shortcuts" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
material = { module = "com.google.android.material:material", version.ref = "material" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup-runtime" }
androidx-compose-bom = { module = 'androidx.compose:compose-bom', version.ref = "compose-bom" }
androidx-compose-ui-main = { module = "androidx.compose.ui:ui" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-material-main = { module = "androidx.compose.material:material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-ui-tooling-main = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-animation-main = { module = "androidx.compose.animation:animation" }
androidx-compose-animation-core = { module = "androidx.compose.animation:animation-core" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }

[bundles]
compose = [
    "androidx-compose-ui-main",
    "androidx-compose-runtime",
    "androidx-compose-material-main",
    "androidx-compose-material-icons-extended",
    "androidx-compose-ui-tooling-main",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-animation-main",
    "androidx-compose-animation-core",
    "androidx-compose-foundation",
    "androidx-activity-compose"
]

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation-safeargs" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

